### PR TITLE
Hotfix/fix UI issues

### PR DESCRIPTION
**Pull request by misterM125**
## Overview

This PR aims to clean the overall ui of the app by changing some colorschemes, fixing ui bugs and refactoring some screens

### ColorPalette changes

The color palette for buttons and dasboard bar have been changed to make the button's contents more visible

### Screen changes
- Added spacing between the `topAppBar` actions
- Removed arbitrary size for the park overview "create an event" button to avoid text clipping on certain phone sizes. The button will now resize depending on the text and size of the screen
- Center the screen content of the "add friend" bluetooth screen to make it more symmetrical and reduce blank spaces
- Changed Button Arrangement in the profile screen to conform to the figma

## How to review

Simply browse the app, as this PR aims to clean the overall ui i would appreciate any suggestion on what you think could be improved in any of the screens' overall appearance

### CODE REVIEW

**Review by Alex720p — CHANGES_REQUESTED** [review]
Looks good.

Something that would be great to implement is to force the app in vertical (the user can't tilt his screen). Also changing the color of the position of the user in the map might be good idea, it's hard to see it now since the markers are also blue.

Here's other some suggestions, I'll let you decide if you think they're relevant/worth the time:
- Make the create event button fit on one line for smaller screens, it looks big and clunky on 2 lines.
park_overview_small

You can do the scaling below with a BoxWithConstraints but I really don't think it's worth the time, it already looks good on modern devices.
- Scaling down the park images & the park rating row for smaller screens. It's a bit hard to see events.
- Scaling down the size of the profile icon depending on screen sizes.
- Scaling down the size of the progression bar & 2 cards depending on screen sizes

**Comment by alvaro1080** [comment]
> Looks good.
> 
> Something that would be great to implement is to force the app in vertical (the user can't tilt his screen). Also changing the color of the position of the user in the map might be good idea, it's hard to see it now since the markers are also blue.
> 
> Here's other some suggestions, I'll let you decide if you think they're relevant/worth the time:
> 
> * Make the create event button fit on one line for smaller screens, it looks big and clunky on 2 lines.
> 
> park_overview_small
> You can do the scaling below with a BoxWithConstraints but I really don't think it's worth the time, it already looks good on modern devices.
> 
> * Scaling down the park images & the park rating row for smaller screens. It's a bit hard to see events.
> * Scaling down the size of the profile icon depending on screen sizes.
> * Scaling down the size of the progression bar & 2 cards depending on screen sizes

About the size of the create a button : We could perhaps remove it and change it to a floating action button with a "plus" (similar to the one we did in the bootcamp). Perhaps no text and just a plus could be enough, since we now have a tutorial part in case it is not clear

**Comment by Alex720p** [comment]
> > Looks good.
> > Something that would be great to implement is to force the app in vertical (the user can't tilt his screen). Also changing the color of the position of the user in the map might be good idea, it's hard to see it now since the markers are also blue.
> > Here's other some suggestions, I'll let you decide if you think they're relevant/worth the time:
> > 
> > * Make the create event button fit on one line for smaller screens, it looks big and clunky on 2 lines.
> > 
> > park_overview_small
> > You can do the scaling below with a BoxWithConstraints but I really don't think it's worth the time, it already looks good on modern devices.
> > 
> > * Scaling down the park images & the park rating row for smaller screens. It's a bit hard to see events.
> > * Scaling down the size of the profile icon depending on screen sizes.
> > * Scaling down the size of the progression bar & 2 cards depending on screen sizes
> 
> About the size of the create a button : We could perhaps remove it and change it to a floating action button with a "plus" (similar to the one we did in the bootcamp). Perhaps no text and just a plus could be enough, since we now have a tutorial part in case it is not clear

Having an floating action button would hide the about button for the last event. But what about replacing the button by an IconButton instead? We could use an icon like this one for ex: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:calendar_add_on:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=event&icon.size=24&icon.color=%23e8eaed&icon.platform=android

**Comment by alvaro1080** [comment]
> > > Looks good.
> > > Something that would be great to implement is to force the app in vertical (the user can't tilt his screen). Also changing the color of the position of the user in the map might be good idea, it's hard to see it now since the markers are also blue.
> > > Here's other some suggestions, I'll let you decide if you think they're relevant/worth the time:
> > > 
> > > * Make the create event button fit on one line for smaller screens, it looks big and clunky on 2 lines.
> > > 
> > > park_overview_small
> > > You can do the scaling below with a BoxWithConstraints but I really don't think it's worth the time, it already looks good on modern devices.
> > > 
> > > * Scaling down the park images & the park rating row for smaller screens. It's a bit hard to see events.
> > > * Scaling down the size of the profile icon depending on screen sizes.
> > > * Scaling down the size of the progression bar & 2 cards depending on screen sizes
> > 
> > 
> > About the size of the create a button : We could perhaps remove it and change it to a floating action button with a "plus" (similar to the one we did in the bootcamp). Perhaps no text and just a plus could be enough, since we now have a tutorial part in case it is not clear
> 
> Having an floating action button would hide the about button for the last event. But what about replacing the button by an IconButton instead? We could use an icon like this one for ex: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:calendar_add_on:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=event&icon.size=24&icon.color=%23e8eaed&icon.platform=android

You are right, I did not think about the problem of hiding the about button. The IconButton looks nice, I think it is a good idea to try it!

**Comment by misterM125** [comment]
So after testing different implementations i wasn't convinced by the icon button, it felt a bit small on the screen and left a lot of blank space next to it, i instead decided to more simply change the button text from "create an event" to "add an event" which is shorter, making it now fully fit in one line even on small screens ( i know this is a bit arbitrary but i tested with the smallest phone screen we can have in android studio and it works so i am going to assume it'll fit in most screens for now

**Review by Alex720p — APPROVED** [review]

**Pull request merged**
